---
title: "HKU SOCI7016 - Quantitative research methods"
subtitle: "2025 Fall"
author:
    - name: Kwan To Wong
      email: kwanto@hku.hk

format:
  html:
    theme: cosmo
    html-math-method: katex
    
---

## Course details

|           | Day       | Time              | Location                       |
|-----------|-----------|-------------------|--------------------------------|
| Lectures  | TBA       | 7pm - 9:50pm      | TBA                            |


## Course objectives

In this course, you will learn the basics of quantitative methods as applied to the social sciences. This involves two broad skill sets. First, a good command of the conceptual foundations of statistics is essential to understand why social scientists analyze data in some specific ways. Second, a hands-on experience in the computing and programming tools (R in our course) to both manage and analyze data is crucial to be able to apply the conceptual foundations of statistics to real-world data.

## Course learning outcomes

At the end of the course you should be able to:

+ Summarize and visualize data
+ Wrangle data into tidy forms
+ Use R for data analysis
+ Understand the basic concepts of probability and statistics
+ Quantify uncertainty in data analysis
+ Be able to use regression models to analyze data

## Assessment Strategies

+ Class participation (10%)
+ Assignments (18%)
+ `Midterm` (42%)
+ Final project presentation (30%)

## Course schedule

| Week | Date             | Topic                                                                 |
|------|------------------|----------------------------------------------------------------------|
| 1    | 2025-09-??       | Overview and Introduction to R                                        |
| 2    | 2025-09-??       | Data visualization                              |
| 3    | 2025-09-??       | Data wrangling                                  |
| 4    | 2025-09-??       | Probability and distributions                                         |
| 5    | 2025-10-??       | Sampling distributions                |
| 6    | 2025-10-??       | Confidence intervals and Hypothesis testing                                     |
| 7    | 2025-10-19       | Reading Week                              |
| 8    | 2025-10-??       | Linear regression I                                  |
| 9    | 2025-10-??       | Linear regression II                                                       |
| 10   | 2025-11-??       | Logistic regression and more                               |
| 11   | 2025-11-??       | Fixed-effects and DID                                         |
| 12   | 2025-11-??       | Midterm                               |
| 13   | 2025-11-??       | Final project presentations                                          |


## Final project presentation

The final project presentation is an opportunity for you to present your final project to the class. Each group will have a group of 4 students, with plus/minus 1 flexibility. This is a `data analysis` project about a particular topic excites you. No matter what the topic your group choose, your group need formula at least one key research question, find data to answer that question by using the quantitative methods, and present those results for educated public consumption.  The presentation should include the following:

+ An introduction to the research question
+ An overview of the data, including its source, collection method, and any relevant background information
+ An overview of the methods used
+ A discussion of the results
+ A brief discussion of the implications of the research for theory, policy or practice
+ A conclusion
+ A brief discussion of the limitations of the study (optional)
+ A brief discussion of the future directions of the research (optional)


## Reference

I will draw materials from the following books in this course:

+ Imai, Kosuke and Nora Webb Willaims. 2022. Quantitative Social Science: An Introduction with Tidyverse, 2022. Princeton University Press.

+ Ismay, Chester and Albert Y. Kim. 2022. Statistical Inference via Data Science: A ModernDive into R and the Tidyverse.


## Late Policy

+ For problem sets, late submissions will be penalized two sub-grade if submitted 0-24 hours late and penalized 4 sub-grade if submitted 24-48 hours late. We will not accept any submissions after 48 hours --- we will get F for the assignment.

## Academic Integrity

The work that you do in the assignments should be your own work. You may seek help from others (including AI) so long as this does not result in someone else (like AI) completing your work for you. You should never copy and paste code from another student or elsewhere (e.g. websites, classmates, AI).

There is no collaboration allowed on the exam.


```{r}
#| echo: False
#| eval: False
#usethis::create_github_token()

gitcreds::gitcreds_set()

```
